version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"

  api:
    container_name: api
    image: slarsson/node-test:latest
    ports:
      - "3000:3000"
