name: Deploy

on:
  push:
    branches:
      - slarsson/fix-deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build containers
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: | 
          docker build -t slarsson/tddd27 .
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push slarsson/tddd27:latest
    
      - name: Build frontend
        run: |
          cd app
          npm ci
          npm run build

      - name: Sync setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey
          chmod 600 mykey
          rsync -vah -e 'ssh -i mykey -o StrictHostKeyChecking=no' ./deploy/ root@$SSH_HOST:/root/deploy/ --delete
          rsync -vah -e 'ssh -i mykey -o StrictHostKeyChecking=no' ./app/dist/ root@$SSH_HOST:/root/html/ --delete

      - name: Restart containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /root/deploy
            docker-compose pull   
            docker-compose up -d
            docker image prune
