# https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

name: Forward commits to gitlab.liu.se

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Mirror to gitlab.liu.se
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
            git config --global user.name 'Samuel Larsson'
            git config --global user.email 'samlarsson94@gmail.com'
            git remote add mirror https://samla949:$GITLAB_TOKEN@gitlab.liu.se/samla949/my-test.git
            git push mirror ${GITHUB_REF##*/}
